---

- name: ensure tasks run only on selected os releases
  block:

    - name: enable the openh264 library
      ansible.builtin.command:
        cmd: sudo dnf config-manager --enable fedora-cisco-openh264
      when: ansible_distribution_major_version <= "40"

    - name: enable the openh264 library
      ansible.builtin.command:
        cmd: dnf config-manager setopt fedora-cisco-openh264.enabled=1
      when: ansible_distribution_major_version >= "41"

    - name: fix for libdnf issues when installing via urls
      block:

        - name: install rpm fusion repositories
          ansible.builtin.dnf:
            name: "{{ rpmfusion_repo }}"
            state: present
            disable_gpg_check: true

      rescue:

        - name: install rpm fusion repositories via dnf
          ansible.builtin.command:
            cmd: "dnf install -y {{ rpmfusion_repo | join(' ') }}"

  when: ansible_distribution == "Fedora"

...
