---

- name: ensure tasks run only on selected os releases
  block:

    - name: enable the openh264 library
      ansible.builtin.command:
        cmd: sudo dnf config-manager --enable fedora-cisco-openh264
      when: ansible_distribution_major_version <= "40"

    - name: enable the openh264 library
      ansible.builtin.command:
        cmd: dnf config-manager setopt fedora-cisco-openh264.enabled=1
      when: ansible_distribution_major_version >= "41"

    - name: install rpm fusion repositories
      ansible.builtin.dnf:
        name:
          - https://mirrors.rpmfusion.org/free/{{ ansible_distribution | lower }}/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
          - https://mirrors.rpmfusion.org/nonfree/{{ ansible_distribution | lower }}/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
        disable_gpg_check: true

  when: ansible_distribution == "Fedora"

...
